# Only for the reviewed manual Barman v0.15.0 layout; see ../../README.md.
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: plugin-barman-cloud
  namespace: flux-system
spec:
  postRenderers:
    - kustomize:
        patches:
          - target:
              group: apps
              version: v1
              kind: Deployment
              name: plugin-barman-cloud
              namespace: cnpg-system
            patch: |-
              - op: replace
                path: /metadata/name
                value: barman-cloud
              - op: replace
                path: /spec/selector/matchLabels
                value:
                  app: barman-cloud
          - target:
              version: v1
              kind: Service
              name: barman-cloud
              namespace: cnpg-system
            patch: |-
              - op: replace
                path: /spec/selector
                value:
                  app: barman-cloud
          - target:
              group: rbac.authorization.k8s.io
              version: v1
              kind: Role
              name: plugin-barman-cloud-leader-election-role
              namespace: cnpg-system
            patch: |-
              - op: replace
                path: /metadata/name
                value: barman-plugin-leader-election-role
          - target:
              group: rbac.authorization.k8s.io
              version: v1
              kind: RoleBinding
              name: plugin-barman-cloud-leader-election-rolebinding
              namespace: cnpg-system
            patch: |-
              - op: replace
                path: /metadata/name
                value: barman-plugin-leader-election-rolebinding
              - op: replace
                path: /roleRef/name
                value: barman-plugin-leader-election-role
