# Supported values for the unchanged official plugin-barman-cloud chart 0.8.0.
apiVersion: v1
kind: ConfigMap
metadata:
  name: pgcf-plugin-barman-cloud-values
  namespace: flux-system
data:
  values.yaml: |
    replicaCount: 1
    logLevel: debug
    image:
      tag: v0.15.0
    sidecarImage:
      tag: v0.15.0
    crds:
      create: true
    service:
      name: barman-cloud
      port: 9090
    serviceAccount:
      create: true
      name: plugin-barman-cloud
    rbac:
      create: true
    podLabels:
      app: barman-cloud
    certificate:
      createClientCertificate: true
      createServerCertificate: true
      createIssuer: true
      issuerName: selfsigned-issuer
      duration: 2160h
      renewBefore: 360h
