---
apiVersion: v1
kind: List
items:
- apiVersion: monitoring.coreos.com/v1
  kind: PodMonitor
  metadata:
    name: pgcf-flux
    namespace: pgcf-monitoring
    labels:
      release: pgcf-telemetry
  spec:
    namespaceSelector:
      matchNames:
      - flux-system
    selector:
      matchExpressions:
      - key: app
        operator: In
        values:
        - source-controller
        - kustomize-controller
        - helm-controller
        - notification-controller
    podMetricsEndpoints:
    - port: http-prom
      path: "/metrics"
      interval: 45s
      honorLabels: false
      relabelings:
      - targetLabel: pgcf_component
        replacement: flux
- apiVersion: monitoring.coreos.com/v1
  kind: PodMonitor
  metadata:
    name: pgcf-cnpg-operator
    namespace: pgcf-monitoring
    labels:
      release: pgcf-telemetry
  spec:
    namespaceSelector:
      matchNames:
      - cnpg-system
    selector:
      matchLabels:
        app.kubernetes.io/name: cloudnative-pg
    podMetricsEndpoints:
    - port: metrics
      path: "/metrics"
      interval: 45s
      honorLabels: false
      relabelings:
      - targetLabel: pgcf_component
        replacement: cnpg-operator
