// SPDX-License-Identifier: Apache-2.0
import {test} from "node:test";
import assert from "node:assert/strict";
import {randomBytes} from "node:crypto";
import versions from "../../platform/versions.lock.json" with {type:"json"};
import {encryptedSwapDocuments,type SwapQualificationInput} from "./configuration.ts";
const input=():SwapQualificationInput=>({machine_type:"worker",isolated_worker_accepted:true,talos_version:versions.target.talosVersion,kubernetes_version:versions.target.kubernetesVersion,largest_verified_tail_bytes:10727981056,swap_bytes:4*1073741824,passphrase:randomBytes(32).toString("base64url")});
test("only a qualified isolated worker can render bounded encrypted swap without touching data partitions",()=>{const value=input(),result=encryptedSwapDocuments(value);assert.equal(result.machine_patch.machine.kubelet.extraConfig.memorySwap.swapBehavior,"LimitedSwap");assert.equal(result.documents.length,1);assert.deepEqual(result.documents[0]?.provisioning,{diskSelector:{match:"system_disk"},grow:false,minSize:"4096MiB",maxSize:"4096MiB"});assert.equal(result.documents[0]?.encryption?.provider,"luks2");assert.equal(result.documents[0]?.encryption?.keys[0]?.static.passphrase,value.passphrase);assert.throws(()=>encryptedSwapDocuments({...value,machine_type:"controlplane"}),/not_qualified/);assert.throws(()=>encryptedSwapDocuments({...value,isolated_worker_accepted:false}),/not_qualified/);});
test("insufficient geometry and unsupported software cannot suggest shrinking or disabling checks",()=>{const value=input();assert.throws(()=>encryptedSwapDocuments({...value,largest_verified_tail_bytes:value.swap_bytes-1}),/unpartitioned/);assert.throws(()=>encryptedSwapDocuments({...value,talos_version:"1.0.0"}),/not_qualified/);assert.throws(()=>encryptedSwapDocuments({...value,passphrase:"unsafe"}),/private_random/);const compressed=encryptedSwapDocuments({...value,zswap_percent:10});assert.equal(compressed.documents[1]?.kind,"ZswapConfig");});
