apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../existing-helm
patches:
  - path: release-compatibility.yaml
  - path: values-compatibility.yaml
  - target:
      group: helm.toolkit.fluxcd.io
      version: v2
      kind: HelmRelease
      name: cloudnative-pg
    patch: |-
      - op: remove
        path: /spec/suspend
