replicaCount: 1
image:
  tag: v0.15.1
sidecarImage:
  tag: v0.15.1
crds:
  create: true
certificate:
  createClientCertificate: true
tolerations:
  - key: pgcf.io/quarantine
    operator: Exists
    effect: NoSchedule
