// SPDX-License-Identifier: Apache-2.0
// Generated by packages/contracts/native/generate.ts. Do not edit.
pub const MAX_PAYLOAD_BYTES: usize = 33554432;
pub const MAX_FRAME_BYTES: usize = 65536;
pub const MAX_STARTUP_BUFFER_BYTES: usize = 65536;
