// SPDX-License-Identifier: Apache-2.0
// TEST ONLY public CA, no private key.
export const testCA =
  "-----BEGIN CERTIFICATE-----\nMIIBuTCCAV+gAwIBAgIUHnaQvm3f6gFtGTOm+H5PkCQf9cYwCgYIKoZIzj0EAwIw\nKjEoMCYGA1UEAwwfVEVTVCBPTkxZIFBHQ0YgbmF0aXZlIGFjY2VzcyBDQTAeFw0y\nNjA5MjkxMzI4MDhaFw0zNjA5MjYxMzI4MDhaMCoxKDAmBgNVBAMMH1RFU1QgT05M\nWSBQR0NGIG5hdGl2ZSBhY2Nlc3MgQ0EwWTATBgcqhkjOPQIBBggqhkjOPQMBBwNC\nAAQbGJ7zdLBsMWzAJUzWiZtiJ9QqYfSB0hne2F7QRlLb7hLDtl9LsmsLtAQRV4Nw\n3fNBDTzvQb1fGt/Yi6Oz03zoo2MwYTAdBgNVHQ4EFgQURqQZ9sxyOGoxRxf0hZR8\niFtm/jAwHwYDVR0jBBgwFoAURqQZ9sxyOGoxRxf0hZR8iFtm/jAwDwYDVR0TAQH/\nBAUwAwEB/zAOBgNVHQ8BAf8EBAMCAQYwCgYIKoZIzj0EAwIDSAAwRQIhAKXlHZpq\nb26dGRVMW4Gmwz/+BYqcoqUaSwaI7C7QRYNeAiBOofVGVZbDnI/SxaekZnuvqR6O\nel7mHbF9X9coMb7N+g==\n-----END CERTIFICATE-----\n";
